CFLAGS=-pthread -std=c++11 
LDFLAGS=-lpthread 
CC=g++
LIBDIR=lib

ifeq ($(MODE),debug)
  CFLAGS+= -g -DGGO_DEBUG 
else ifeq ($(MODE),prof)
  CFLAGS+= -pg 
  LDFLAGS+= -pg 
else
  CFLAGS+= -O3 
endif

OS := $(shell uname)
ifeq ($(OS),Linux)
  CFLAGS+= -DLINUX
endif
ifeq ($(OS),Darwin)
  CFLAGS+= -DMACOS 
endif
ifeq ($(OS),CYGWIN_NT-6.1)
  CFLAGS+= -DCYGWIN
endif