CFLAGS=-pthread -std=c++11
LDFLAGS=-lpthread 
CC=g++
LIBDIR=lib

ifeq ($(MODE),debug)
  CFLAGS+= -g -DGGO_DEBUG 
else ifeq ($(MODE),prof)
  CFLAGS+= -pg 
  LDFLAGS+= -pg 
else
  CFLAGS+= -O3 
endif

OS := $(shell uname)
ifeq ($(OS),Linux)
  CFLAGS+= -DGGO_LINUX
endif
ifeq ($(OS),Darwin)
  CFLAGS+= -DGGO_DARWIN
endif
ifeq ($(OS),CYGWIN_NT-10.0)
  CFLAGS+= -DGGO_CYGWIN
endif

rwildcard=$(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2) $(filter $(subst *,%,$2),$d))

